In [9]:
import numpy as np


In [10]:
arr = np.random.random(100000000)

In [11]:
print(arr)

[0.74716464 0.64815777 0.50416684 ... 0.11772575 0.08286135 0.55220043]


In [5]:
size(arr)

NameError: name 'size' is not defined

In [6]:
np.size(arr)

100000000

In [8]:
np.mean(arr)

0.5000386579213378

In [14]:
x = np.array([1,2,3,4,5])

In [15]:
print(x)

[1 2 3 4 5]


In [16]:
x.dtype

dtype('int64')

In [17]:
x.shape

(5,)

In [18]:
y = np.array([1,2,3,4,5],[1,2,3,4,5], [[1,2,3,4,5],2,3,4,5])

ValueError: only 2 non-keyword arguments accepted

In [19]:
y = np.array([1,2,3,4,5],[1,2,3,4,5], [1,2,3,4,5])

ValueError: only 2 non-keyword arguments accepted

In [20]:
y = np.array([[1,2,3,4,5],[1,2,3,4,5], [[1,2,3,4,5],2,3,4,5])

SyntaxError: invalid syntax (<ipython-input-20-859428cd0e64>, line 1)

In [21]:
y = np.array([[1,2,3,4,5],[1,2,3,4,5], [[1,2,3,4,5],2,3,4,5]])

In [23]:
y.shape

(3, 5)

In [24]:
print(y)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [list([1, 2, 3, 4, 5]) 2 3 4 5]]


In [26]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.full((3,4), 12)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [28]:
X = np.eye(5)

In [29]:
X

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.diat([10,20,30,40])

AttributeError: module 'numpy' has no attribute 'diat'

In [31]:
np.diag([10,20,30,40])

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [35]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [36]:
np.diat([10,20,30,40])

AttributeError: module 'numpy' has no attribute 'diat'

In [37]:
x


array([1, 2, 3, 4, 5])

In [38]:
x[-3]

3